# Global configuration values shared across all components
global:
  imageRegistry: docker.io
  imagePullPolicy: IfNotPresent
  storageClass: standard
  nodeSelector:
    monitoring: "true"
  podSecurityContext:
    fsGroup: 65534
    runAsUser: 65534
    runAsNonRoot: true
  networkPolicy:
    enabled: true

# Prometheus configuration for metrics collection and storage
prometheus:
  enabled: true
  server:
    retention: 30d
    replicaCount: 2
    persistentVolume:
      enabled: true
      size: 100Gi
      storageClass: standard
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    securityContext:
      enabled: true
      runAsUser: 65534
      runAsNonRoot: true
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
  alertmanager:
    enabled: true
    replicaCount: 2
    persistence:
      enabled: true
      size: 10Gi
    securityContext:
      enabled: true
      runAsUser: 65534
      runAsNonRoot: true

# Grafana configuration for visualization and dashboards
grafana:
  enabled: true
  adminPassword: ${GRAFANA_ADMIN_PASSWORD}
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  securityContext:
    enabled: true
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
  dashboardProviders:
    providers:
      - name: default
        folder: Nexus Platform
        type: file
        options:
          path: /var/lib/grafana/dashboards
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      enabled: true

# Jaeger configuration for distributed tracing
jaeger:
  enabled: true
  collector:
    replicaCount: 2
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-master:9200
        tls:
          enabled: true
  agent:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

# Elasticsearch configuration for log aggregation
elasticsearch:
  enabled: true
  replicas: 3
  persistence:
    enabled: true
    size: 100Gi
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  security:
    enabled: true
    tls:
      enabled: true
      autoGenerated: true
    authentication:
      enabled: true
      passwordSecret: elasticsearch-credentials
  antiAffinity: hard
  initResources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi