# Helm v3 Chart definition for Nexus Platform Shipping Service
apiVersion: v2
name: shipping-service
version: 1.0.0
appVersion: 1.0.0
description: Shipping Service for the Nexus B2B Trade Platform - Handles multi-carrier integration, real-time shipment tracking, documentation management, and logistics coordination
type: application

# Keywords for chart discovery and categorization
keywords:
  - shipping
  - logistics
  - tracking
  - documentation
  - carrier-integration
  - trade-platform

# Chart maintainer information
maintainers:
  - name: Nexus Platform Team
    email: platform@nexus.com

# Chart dependencies
dependencies:
  - name: redis
    version: 17.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 23.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled

# Additional metadata
home: https://nexus.com/platform/shipping
sources:
  - https://github.com/nexus/platform
kubeVersion: ">=1.20.0"
annotations:
  category: Infrastructure