{{/* Kubernetes Ingress resource for Nexus B2B Platform */}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.global.security.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.global.security.tls.issuer.name }}
    {{- end }}
    # Security headers
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
      more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'";
    # Rate limiting
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/limit-connections: "50"
    # Session affinity
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "NEXUS_ROUTE"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    # Load balancing
    nginx.ingress.kubernetes.io/load-balance: "ewma"
    # Monitoring
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"

spec:
  {{- if .Values.global.security.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.global.domain }}
    {{- range .Values.ingress.additionalHosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ template "nexus.fullname" . }}-tls
  {{- end }}
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      # API Gateway path
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "nexus.fullname" . }}-api-gateway
            port:
              number: 80
      # Health check endpoint
      - path: /health
        pathType: Exact
        backend:
          service:
            name: {{ template "nexus.fullname" . }}-api-gateway
            port:
              number: 80
      # Metrics endpoint (protected)
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: {{ template "nexus.fullname" . }}-api-gateway
            port:
              number: 80
  {{- range .Values.ingress.additionalHosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "nexus.fullname" . }}-api-gateway
            port:
              number: 80
  {{- end }}