{{/* Secret template for Nexus platform with enhanced security features */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  annotations:
    security.nexus.io/compliance: "pci-dss,iso-27001"
    security.nexus.io/rotation: "{{ .Values.global.security.secretRotation | default "30d" }}"
    security.nexus.io/audit: "enabled"
    security.nexus.io/environment: "{{ .Values.global.environment }}"
    security.nexus.io/region: "{{ .Values.global.region }}"
    security.nexus.io/last-rotated: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"
    security.nexus.io/checksum: "{{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}"
type: Opaque
data:
  # Database credentials
  {{- if .Values.global.database }}
  database.host: {{ required "Database host is required" .Values.global.database.host | b64enc | quote }}
  database.port: {{ required "Database port is required" .Values.global.database.port | toString | b64enc | quote }}
  database.username: {{ required "Database username is required" .Values.global.database.username | b64enc | quote }}
  database.password: {{ required "Database password is required" .Values.global.database.password | b64enc | quote }}
  {{- end }}

  # Redis credentials
  {{- if .Values.global.redis }}
  redis.host: {{ required "Redis host is required" .Values.global.redis.host | b64enc | quote }}
  redis.password: {{ required "Redis password is required" .Values.global.redis.auth.password | b64enc | quote }}
  {{- end }}

  # Kafka credentials
  {{- if .Values.global.kafka }}
  kafka.brokers: {{ required "Kafka brokers list is required" .Values.global.kafka.brokers | b64enc | quote }}
  {{- if .Values.global.kafka.auth.sasl }}
  kafka.sasl.username: {{ required "Kafka SASL username is required" .Values.global.kafka.auth.sasl.username | b64enc | quote }}
  kafka.sasl.password: {{ required "Kafka SASL password is required" .Values.global.kafka.auth.sasl.password | b64enc | quote }}
  {{- end }}
  {{- end }}

  # OAuth2/Security credentials
  {{- if .Values.global.security }}
  {{- if .Values.global.security.oauth2 }}
  oauth2.client-id: {{ required "OAuth2 client ID is required" .Values.global.security.oauth2.clientId | b64enc | quote }}
  oauth2.client-secret: {{ required "OAuth2 client secret is required" .Values.global.security.oauth2.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.security.jwt }}
  jwt.secret-key: {{ required "JWT secret key is required" .Values.global.security.jwt.secretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.security.encryption }}
  encryption.key: {{ required "Encryption key is required" .Values.global.security.encryption.key | b64enc | quote }}
  {{- end }}
  {{- end }}

  # External service credentials
  {{- if .Values.payment-service }}
  {{- if .Values.payment-service.stripe }}
  stripe.api-key: {{ required "Stripe API key is required" .Values.payment-service.stripe.apiKey | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- if .Values.notification-service }}
  {{- if .Values.notification-service.sendgrid }}
  sendgrid.api-key: {{ required "SendGrid API key is required" .Values.notification-service.sendgrid.apiKey | b64enc | quote }}
  {{- end }}
  {{- end }}

  # AWS credentials
  {{- if .Values.global.aws }}
  aws.access-key: {{ required "AWS access key is required" .Values.global.aws.accessKey | b64enc | quote }}
  aws.secret-key: {{ required "AWS secret key is required" .Values.global.aws.secretKey | b64enc | quote }}
  {{- end }}