{{/* ServiceAccount template for Nexus platform services */}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nexus.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  annotations:
    # Security annotations for service account token management
    security.nexus.io/token-rotation: "enabled"
    security.nexus.io/token-expiry: "24h"
    security.nexus.io/token-audience: "{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local"
    security.nexus.io/token-automount: "true"
    
    # Service mesh integration annotations
    istio.io/inject: "true"
    sidecar.istio.io/inject: "true"
    
    # Monitoring and observability annotations
    monitoring.nexus.io/enabled: "true"
    monitoring.nexus.io/scrape: "true"
    
    # Compliance and audit annotations
    audit.nexus.io/enabled: "true"
    compliance.nexus.io/pci-dss: "enabled"
    compliance.nexus.io/gdpr: "enabled"
    
    # Kubernetes service account specific annotations
    kubernetes.io/enforce-mountable-secrets: "true"
    {{- if .Values.global.security.tls.enabled }}
    kubernetes.io/tls-enabled: "true"
    {{- end }}
    
    # Cloud provider specific annotations
    {{- if eq .Values.global.environment "production" }}
    iam.gke.io/workload-identity: "{{ .Release.Namespace }}.svc.id.goog"
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.global.aws.accountId }}:role/{{ .Release.Name }}-{{ .Release.Namespace }}"
    {{- end }}

automountServiceAccountToken: true

{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}

{{- if .Values.serviceAccount.secrets }}
secrets:
{{- range .Values.serviceAccount.secrets }}
  - name: {{ . }}
{{- end }}
{{- end }}

{{- if eq .Values.global.environment "production" }}
# Production-specific security policies
securityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  {{- if .Values.global.security.seccompProfile }}
  seccompProfile:
    type: RuntimeDefault
  {{- end }}
{{- end }}