# Helm v3 Chart definition for Nexus Authentication Service
apiVersion: v2
name: auth-service
version: 1.0.0
type: application
appVersion: "1.0.0"

description: Authentication Service for Nexus B2B Platform - Provides OAuth 2.0 + OIDC based authentication and authorization with JWT tokens, refresh token rotation, and high availability support

keywords:
  - authentication
  - oauth2
  - oidc
  - jwt
  - security
  - high-availability
  - multi-region

maintainers:
  - name: Nexus Platform Team
    email: platform@nexus.com

# Dependencies required for the auth service
dependencies:
  - name: redis
    version: 17.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    # Redis is used for session storage, token caching, and high-availability state management
    
  - name: postgresql
    version: 12.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    # PostgreSQL is used for user credentials, token storage, and audit logging persistence